apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: k8s-autoscaling-demo-vpa
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: k8s-autoscaling-demo
  updatePolicy:
    updateMode: "Auto"
